### ISSUE TITLE
Update Lightning payment flows

### ISSUE THREAD

**Issue by rockymedure** [stemstr/Design#7]
Update the UX of the lightning payment flows to include
- pay via qr scan on desktop
- pay via wallet deeplink on mobile 

This should work for
- sharing a sound 
- downloading a sound
- zapping

**Comment by robagreda** [comment]
How can I help with this crucial task? :)

**Comment by rockymedure** [comment]
I'll take this flow! I'd rather you keep jamming on the "explore bitcoin" and "explore nostr" parts of the onboarding. Wanna get together towards the end of this week and review this lightning flow and your onboarding flows?
